name: Build + test (no download)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build-and-test-pr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: bash ci/build-and-test-pr.sh
        shell: bash
        env:
          CASE_publish: false
          NODE_VERSION: ${{ matrix.node-version }}
          FORCE_COLOR: true
