on:
  push:
    branches: [main]

name: Test Coveralls

jobs:
  build:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@db19848a5fa7950289d3668fb053140cf3028d43 # pin@v3.3.2
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3.3.2
      - run: npm install -g npm@latest

      - name: test
        run: |
          ./ci/coverage.sh
        env:
          CASE_BROKER_CI_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
          CASE_BROKER_BASEURL: https://timothyjones.pactflow.io/
          FORCE_COLOR: true

      - name: Coveralls Core
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: 'packages/case-core/combined-coverage.info'
          base-path: 'packages/case-core'
          github-token: ${{ secrets.GITHUB_TOKEN }}
