on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: release
        with:
          token: ${{ secrets.RATE_TOKEN_GH }}

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

  publish:
    needs: [release-please]
    runs-on: ubuntu-lates
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      # The logic below handles the npm publication:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Set up JDK 17
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'
      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@473878a77f1b98e2b5ac4af93489d1656a80a5ed # v4.2.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0
      - name: Build Packages
        run: ci/build-and-test.sh
        env:
          CASE_BROKER_CI_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
          CASE_BROKER_BASEURL: https://timothyjones.pactflow.io/
          NODE_VERSION: 22
          FORCE_COLOR: true

    # Release Please has already incremented versions and published tags, so we just
    # need to publish all unpublished versions to NPM here
    # See: https://github.com/lerna/lerna/tree/main/commands/publish#bump-from-package
    #  - name: Publish to NPM
    #    if: ${{ needs.release-please.outputs.release_created }}
    #    env:
    #      NODE_AUTH_TOKEN: ${{secrets.CONTRACT_CASE_NPM}}
    #    run: npx lerna publish from-package --no-push --no-private --yes
