on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RATE_TOKEN_GH }}

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

  publish:
    needs: [release-please]
    runs-on: ubuntu-latest
    steps:
      # The logic below handles the npm publication:
      - name: Checkout Repository
        if: ${{ needs.release-please.outputs.release_created }}
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        if: ${{ needs.release-please.outputs.release_created }}
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - run: npm install -g npm@latest
      - name: Build Packages
        if: ${{ needs.release-please.outputs.release_created }}
        run: ci/build-and-test.sh
        env:
          CASE_BROKER_CI_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
          CASE_BROKER_BASEURL: https://timothyjones.pactflow.io/
          NODE_VERSION: 18
          FORCE_COLOR: true

    # Release Please has already incremented versions and published tags, so we just
    # need to publish all unpublished versions to NPM here
    # See: https://github.com/lerna/lerna/tree/main/commands/publish#bump-from-package
    #  - name: Publish to NPM
    #    if: ${{ needs.release-please.outputs.release_created }}
    #    env:
    #      NODE_AUTH_TOKEN: ${{secrets.CONTRACT_CASE_NPM}}
    #    run: npx lerna publish from-package --no-push --no-private --yes
